export const templateConfig = {
  completion: {
    label: '工事完了報告書',
    templateVersion: 'completion-form-v1',
    source: '完了報告書.pdf / 完了報告書.xlsx',
    sourcePdf: '完了報告書.pdf',
    sourceXlsx: '完了報告書.xlsx',
    replacementKey: 'completion',
    background: './templates/completion-report.png',
  },
  marusan: {
    label: '丸産報告書',
    templateVersion: 'marusan-form-v1',
    source: '丸産報告書.pdf / 丸産報告書.xlsx',
    sourcePdf: '丸産報告書.pdf',
    sourceXlsx: '丸産報告書.xlsx',
    replacementKey: 'marusan',
    background: './templates/marusan-report.png',
  },
  receiptBox: {
    label: '領収書添付',
    source: '工事完了報告書の領収書欄',
    imageMode: 'first-image-to-formal-slot-plus-additional-attachments',
    preserveOriginal: true,
  },
}

const inferTemplate = sourceKey => sourceKey.startsWith('ms_') || sourceKey.startsWith('workSlot')
  || ['year', 'month', 'day', 'amTime', 'pmTime', 'notes', 'submittedAt', 'submittedYear', 'submittedMonth', 'submittedDay'].includes(sourceKey)
  ? 'marusan' : 'completion'

const existing = (formName, sourceKey, tag, field = sourceKey) => ({
  formName, sourceKey, tag, field, template: inferTemplate(sourceKey), origin: '現行AppSheet', status: '既存項目',
})

const newField = (formName, sourceKey, tag, field = sourceKey) => ({
  formName, sourceKey, tag, field, template: inferTemplate(sourceKey), origin: '新台紙', status: '新規項目',
})

export const tagRegistry = [
  existing('提出日', 'ms_date', '<<ms_date>>', 'submittedAt'),
  existing('AM', 'ms_am_time', '<<ms_am_time>>', 'amTime'),
  existing('PM', 'ms_pm_time', '<<ms_pm_time>>', 'pmTime'),
  existing('作業内容1', 'ms_work2', '<<ms_work2>>', 'workContent'),
  existing('作業内容2', 'ms_work3', '<<ms_work3>>', 'workContent'),
  existing('作業内容3', 'ms_work4', '<<ms_work4>>', 'workContent'),
  newField('完了／未完', 'completionStatus', '<<completionStatus>>'),
  newField('回数', 'occurrence', '<<occurrence>>'),
  newField('応援者', 'supporters', '<<supporters>>'),
  newField('駐車場代', 'parkingFee', '<<parkingFee>>'),
  newField('高速代', 'tollMode', '<<tollMode>>'),
  newField('高速料金検索リンク', 'tollLink', '<<tollLink>>'),
  newField('材料費（丸産駐車場）', 'materialCost', '<<materialCost>>'),
  newField('建新1', 'construction1', '<<construction1>>'),
  newField('建新2', 'construction2', '<<construction2>>'),
  newField('材料1', 'material1', '<<material1>>'),
  newField('材料2', 'material2', '<<material2>>'),
  newField('フリー1', 'free1', '<<free1>>'),
  newField('フリー2', 'free2', '<<free2>>'),
  newField('フリー3', 'free3', '<<free3>>'),
  newField('フリー（作業時間）', 'freeTime', '<<freeTime>>'),
  newField('フリー4', 'free4', '<<free4>>'),
  newField('現場日誌など', 'diary', '<<diary>>'),
  existing('会社名', 'toCompany', '<<toCompany>>'),
  existing('営業所', 'toOffice', '<<toOffice>>'),
  existing('担当者', 'toPerson', '<<toPerson>>'),
  existing('作業者', 'workerName', '<<workerName>>'),
  existing('現場名', 'siteName', '<<siteName>>'),
  existing('注文No.', 'orderNo', '<<orderNo>>'),
  existing('住所', 'address', '<<address>>'),
  existing('日付', 'workDate', '<<workDate>>'),
  existing('工事内容1', 'work2', '<<work2>>', 'workContent'),
  existing('工事内容2', 'work3', '<<work3>>', 'workContent'),
  existing('工事内容3', 'work4', '<<work4>>', 'workContent'),
  existing('工事金額', 'constructionTotal', '<<constructionTotal>>', 'total'),
  existing('消費税', 'tax', '<<tax>>'),
  existing('工事担当者', 'ms_personInCharge', '<<ms_personInCharge>>'),
  existing('会社名', 'ms_company', '<<ms_company>>', 'companyName'),
  newField('応援者', 'ms_supporters', '<<ms_supporters>>', 'supporters'),
  existing('現場名および工事内容', 'ms_site', '<<ms_site>>', 'siteName'),
  existing('作業者', 'ms_nameL1', '<<ms_nameL1>>'),
  existing('作業者', 'ms_nameL2', '<<ms_nameL2>>'),
  existing('作業者', 'ms_nameL3', '<<ms_nameL3>>'),
  existing('作業者', 'ms_nameR1', '<<ms_nameR1>>'),
  existing('作業者', 'ms_nameR2', '<<ms_nameR2>>'),
  existing('作業者', 'ms_nameR3', '<<ms_nameR3>>'),
  newField('数量', 'quantity', '<<quantity>>'),
  newField('備考', 'remarks', '<<remarks>>'),
  newField('薬剤使用', 'spray', '<<spray>>'),
  newField('薬剤詳細', 'sprayDetail', '<<sprayDetail>>'),
  newField('通常材料以外に材料を使用した場合', 'specialMaterial', '<<specialMaterial>>'),
  newField('合計金額', 'totalAmount', '<<totalAmount>>'),
  newField('提出日', 'submittedAt', '<<submittedAt>>'),
  newField('提出日（年）', 'submittedYear', '<<submittedYear>>'),
  newField('提出日（月）', 'submittedMonth', '<<submittedMonth>>'),
  newField('提出日（日）', 'submittedDay', '<<submittedDay>>'),
  newField('年', 'year', '<<year>>'),
  newField('月', 'month', '<<month>>'),
  newField('日', 'day', '<<day>>'),
  newField('AM', 'amTime', '<<amTime>>'),
  newField('PM', 'pmTime', '<<pmTime>>'),
  newField('作業内容 AM 1', 'workSlot1', '<<workSlot1>>'),
  newField('作業内容 AM 2', 'workSlot2', '<<workSlot2>>'),
  newField('作業内容 AM 3', 'workSlot3', '<<workSlot3>>'),
  newField('作業内容 PM 1', 'workSlot4', '<<workSlot4>>'),
  newField('作業内容 PM 2', 'workSlot5', '<<workSlot5>>'),
  newField('作業内容 PM 3', 'workSlot6', '<<workSlot6>>'),
  newField('連絡事項・特記事項・翌日の作業予定', 'notes', '<<notes>>'),
]

const placement = (template, sourceKey, x, y, width, height, fontSize = 11, kind) => ({ template, sourceKey, x, y, width, height, fontSize, ...(kind ? { kind } : {}) })

export const tagPlacementDefaults = [
  placement('marusan', 'ms_personInCharge', 53.37, 6.02, 17.4, 2.9, 13),
  placement('marusan', 'ms_date', 23.3, 16.15, 35.6, 2.9, 12),
  placement('marusan', 'ms_site', 21.95, 19.85, 52.2, 2.9, 12),
  placement('marusan', 'ms_am_time', 27.19, 23.56, 19.4, 2.55, 12),
  placement('marusan', 'ms_pm_time', 53.37, 23.56, 19.4, 2.55, 12),
  placement('marusan', 'ms_work2', 21.95, 26.15, 52.8, 2.55, 12),
  placement('marusan', 'ms_work3', 21.91, 28.61, 52.8, 2.55, 12),
  placement('marusan', 'ms_work4', 21.88, 30.96, 52.8, 2.55, 12),
  placement('completion', 'occurrence', 55.5, 9.5, 14, 4.2, 10, 'circle'), placement('completion', 'completionStatus', 78, 13.1, 14, 4.2, 10, 'circle'), placement('completion', 'supporters', 78, 17.6, 16, 3.5, 10),
  placement('completion', 'parkingFee', 69, 22.2, 24, 3.2, 10), placement('completion', 'tollMode', 69, 25.8, 24, 3.2, 10),
  placement('completion', 'materialCost', 69, 29.4, 24, 3.2, 10),
  placement('completion', 'construction1', 27, 57.8, 22, 3.2, 10), placement('completion', 'construction2', 51, 57.8, 20, 3.2, 10),
  placement('completion', 'material1', 5, 81, 22, 3.2, 10), placement('completion', 'material2', 29, 81, 22, 3.2, 10),
  placement('completion', 'free1', 53, 81, 13, 3.2, 10), placement('completion', 'free2', 67, 81, 13, 3.2, 10),
  placement('completion', 'free3', 81, 81, 13, 3.2, 10), placement('completion', 'freeTime', 16, 71.7, 32, 3.2, 10),
  placement('completion', 'free4', 29, 84.6, 22, 3.2, 10), placement('completion', 'diary', 5, 80.3, 89, 7, 9),
  placement('completion', 'toCompany', 20, 17.8, 31, 4, 12), placement('completion', 'toOffice', 20, 24.3, 31, 4),
  placement('completion', 'toPerson', 24, 30, 28, 4), placement('completion', 'workerName', 76, 7.3, 18, 3.5),
  placement('completion', 'workDate', 16, 35.8, 22, 3.2), placement('completion', 'siteName', 40.5, 35.8, 49, 3.2),
  placement('completion', 'orderNo', 21, 42.8, 25, 3.2), placement('completion', 'address', 52, 42.8, 39, 3.2),
  placement('completion', 'work2', 23, 47.5, 26, 3.2), placement('completion', 'work3', 23, 51, 26, 3.2),
  placement('completion', 'work4', 23, 54.6, 26, 3.2), placement('completion', 'quantity', 50, 47.5, 5, 3.2),
  placement('completion', 'remarks', 53, 43.2, 40, 3.2), placement('completion', 'spray', 5, 61.7, 41, 3.2),
  placement('completion', 'sprayDetail', 5, 65.3, 41, 13), placement('completion', 'specialMaterial', 53, 65.3, 40, 13),
  placement('completion', 'constructionTotal', 10, 95.4, 22, 3.2, 12), placement('completion', 'tax', 40, 95.4, 22, 3.2, 12),
  placement('completion', 'totalAmount', 66, 95.4, 28, 3.2, 12),
  placement('marusan', 'submittedYear', 76, 3, 8, 3.5, 10), placement('marusan', 'submittedMonth', 86, 3, 7, 3.5, 10), placement('marusan', 'submittedDay', 95, 3, 5, 3.5, 10), placement('marusan', 'year', 42, 15, 14, 4),
  placement('marusan', 'month', 61, 15, 14, 4), placement('marusan', 'day', 80, 15, 14, 4),
  placement('marusan', 'amTime', 28, 30, 31, 3.5, 10),
  placement('marusan', 'pmTime', 61, 30, 31, 3.5, 10), placement('marusan', 'workSlot1', 28, 33.8, 31, 3.7, 10),
  placement('marusan', 'workSlot2', 28, 37.5, 31, 3.7, 10), placement('marusan', 'workSlot3', 28, 41.2, 31, 3.7, 10),
  placement('marusan', 'workSlot4', 61, 33.8, 31, 3.7, 10), placement('marusan', 'workSlot5', 61, 37.5, 31, 3.7, 10),
  placement('marusan', 'workSlot6', 61, 41.2, 31, 3.7, 10), placement('marusan', 'ms_nameL1', 21.95, 68.23, 26.32, 2.55, 12),
  placement('marusan', 'ms_nameL2', 21.96, 70.59, 26.32, 2.55, 12), placement('marusan', 'ms_nameL3', 21.81, 73.04, 26.32, 2.55, 12),
  placement('marusan', 'ms_nameR1', 48.44, 68.15, 26.32, 2.55, 12), placement('marusan', 'ms_nameR2', 48.55, 70.62, 26.32, 2.55, 12),
  placement('marusan', 'ms_nameR3', 48.52, 73.17, 26.32, 2.55, 12), placement('marusan', 'ms_supporters', 28, 58, 65, 3, 9), placement('marusan', 'notes', 28, 61, 65, 23, 9),
]

export const placementFieldNames = ['x', 'y', 'width', 'height', 'fontSize']
